# Generated by Django 4.1 on 2022-08-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
    ]
