# Generated by Django 4.1 on 2022-08-17 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField()),
                ('city', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('occupation', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
