# Generated by Django 4.1 on 2022-08-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_authorization', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
