# Generated by Django 4.1 on 2022-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_authorization', '0005_alter_userprofile_birthday_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('-', 'None')],
                default='-',
                max_length=10
            ),
        ),
    ]
