# Generated by Django 4.1 on 2022-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_authorization', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
